name: Publish to NPM

on:
  push:
    tags:
      - "3001*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        default: "3001.0.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 20
      - name: Determine version
        id: determine-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            NEW_VERSION="${{ github.event.inputs.version }}"
          else
            NEW_VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Update package.json version
        run: |
          echo "Updating package.json version to $NEW_VERSION"
          jq --arg newVersion "$NEW_VERSION" '.version = $newVersion' package.json > tmp.json && mv tmp.json package.json
      - name: Commit and push changes
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --local user.name "Bag Bot"
          git config --local user.email "lajbel@kaplayjs.com"
          git add .
          git commit -m "chore: bump version" || echo "No changes to commit"
          git push https://x-access-token:$BOT_TOKEN@github.com/${{ github.repository }}.git HEAD:v3001
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
