name: Publish to NPM

on:
  push:
    tags:
      - '3001*' # Publish on tags like 3001.0.0, 3001.0.1-rc.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 20
      - name: Update package.json version
        run: |
          # Update the version in package.json to the new version
          NEW_VERSION=${GITHUB_REF#refs/tags/}
          NEW_VERSION=${NEW_VERSION#3001.}
          NEW_VERSION="3001.$NEW_VERSION"
          echo "Updating package.json version to $NEW_VERSION"
          jq --arg newVersion "$NEW_VERSION" '.version = $newVersion' package.json > tmp.json && mv tmp.json package.json
          
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
